---
# tasks file for preSetup-servers

- name: Initial packages update using raw module # noqa no-changed-when
  raw: apt-get update -y
  tags: raw-debian

- name: Initial packages upgrade using raw module # noqa no-changed-when
  raw: apt-get upgrade -y --no-install-recommends
  tags: raw-debian

- name: Initial python installation using raw module # noqa no-changed-when
  raw: apt-get install -y python3 python3-apt python3-simplejson aptitude --no-install-recommends
  tags: raw-debian

- name: Initial packages update using raw module # noqa no-changed-when
  raw: yum update -y
  tags: raw-redhat

- name: Initial packages upgrade using raw module # noqa no-changed-when
  raw: yum upgrade -y
  tags: raw-redhat

- name: Initial python installation using raw module # noqa no-changed-when
  raw: yum install -y libselinux-python3 python3 python3-simplejson aptitude
  tags: raw-redhat
  
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  tags: debian

#log2ramintall 4 pi pihole logs
- name: Copy log2ram install script
  copy:
    src: log2raminstall.sh
    dest: /home/hostsadmin
    owner: root
    group: root
    mode: '0744'
  tags: install_log2ram

- name: Ensure log2ram service is installed
  shell:  ./log2raminstall.sh >> log2raminstall.log
  args:
    chdir: /home/hostsadmin
    creates: log2raminstall.log

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
  when: reboot_required_file.stat.exists == true