---
# tasks file for roles/iptables
- name: remove mail packages not necessary
  apt:
    name: [bsd-mailx mailutils postfix ssmtp]
    autoremove: yes
    state: absent
  when: ansible_os_family == "Debian"

- name: install fail2ban, iptables-persistent and auditd
  package:
    name:
      - fail2ban
      - iptables-persistent
      - auditd
    state: present
  async: 1200
  poll: 10
  when: not ansible_check_mode

- name: check presence of fail2ban, iptables-persistent and auditd packages
  package:
    name:
      - fail2ban
      - iptables-persistent
      - auditd
    state: present
  when: ansible_check_mode

- name: make fail2ban persistent
  service: name=fail2ban enabled=yes state=started

- name: make sure netfilter-persistent is enabled
  service: name=netfilter-persistent enabled=yes state=started

- name: make sure auditd is enabled
  service: name=auditd enabled=yes state=started

- name: create iptables configuration
  template: src=iptables.conf.j2 dest=/etc/iptables/rules.v4 owner=root group=root mode=0600
  notify:
    - restore-iptables
    - restart docker

- name: create ip6tables configuration
  template: src=ip6tables.conf.j2 dest=/etc/iptables/rules.v6 owner=root group=root mode=0600
  notify:
    - restore-iptables
    - restart fail2ban
    - restart docker

- name: push iptables rsyslog configuration
  copy: src=rsyslog.d-iptables dest=/etc/rsyslog.d/33-iptables.conf
  notify: restart rsyslog

- name: push iptables logrotate configuration
  copy: src=logrotate.d-iptables dest=/etc/logrotate.d/iptables

- name: configuration file for auditd
  template: src=audit.rules.j2 dest=/etc/audit/rules.d/audit.rules owner=root group=root mode=0640
  notify: restart auditd

- name: push specific fail2ban jail configuration file
  template: src=jail.{{ ansible_distribution }}{{ ansible_distribution_major_version }}.j2 dest=/etc/fail2ban/jail.d/jail.local
  when: ansible_os_family == "Debian" and no_fail2ban is not defined
  notify: restart fail2ban
  tags: fail2ban